from custom.gpt2 import GPT2LMHeadModel
from custom.gptj import GPTJForCausalLM
from custom.bert import BertForMaskedLM

gptj_config_qa = {
    'model': 'gptj',
    'structure': 'uni',
    'task_name': 'qa',
    'device': 'cuda:0',
    'distributed_device': "0,1",
    'top_num': 3,
    'locate_method': 'ig',
    'erase_method': 'kv',
    'ca_ppl_delta': 0.1,
    'num_cuts': 10,
    'decomposite': 'KV',
    'modify_weight': 'KV',
    'name_mlp': 'transformer.h.{}.mlp',
    'subname_K': 'fc_in',
    'subname_V': 'fc_out',
    'subname_act': 'act',
    'intermediate_size': 16384,
    'low_rank': True,
    'num_layers': 28,
    'lambda': 1,
    'ortho_coef': 1,
    'entro_coef': 1,
    'recon_coef': 1,
    'lr': 1e-4,
    'num_epochs': 100,
    'chunk_size': 4,
    'num_local': 100,
    'seed': 42,
    'sample_rate': 0.1,
    'index_wise': True,
    'apply_model_rewriting': True,
    'skip_first_layer': True,
    'skip_last_layer': True,
    'log_file': 'logs/logs_qa_gptj.txt',
    'data_dir': 'data',
    'result_path': 'result',
    'local_data_dir': 'data/wikipedia',
    'sample_file': None,
    "attribution_map_path": "temp/qa/gpt-j-6b/attribution_map",
    'neuron_path': 'temp/qa/gpt-j-6b/neurons-ca-10-grad.pt',
    'weight_path': 'temp/qa/gpt-j-6b/weights.npz',
}

gptj_config_debias = {
    'model': 'gptj',
    'structure': 'uni',
    'task_name': 'qa',
    'device': 'cuda:1',
    'distributed_device': "0,1",
    'locate_method': 'ca',
    'erase_method': 'kv',
    'ca_ppl_delta': 0.2,
    'num_cuts': 10,
    'decomposite': 'KV',
    'modify_weight': 'KV',
    'name_mlp': 'transformer.h.{}.mlp',
    'subname_K': 'fc_in',
    'subname_V': 'fc_out',
    'subname_act': 'act',
    'intermediate_size': 16384,
    'low_rank': True,
    'num_layers': 28,
    'lr': 1e-4,
    'num_epochs': 100,
    'chunk_size': 4,
    'num_local': 100,
    'seed': 42,
    'sample_rate': 1,
    'index_wise': True,
    'apply_model_rewriting': True,
    'skip_first_layer': True,
    'skip_last_layer': True,
    'log_file': 'logs/logs_debias.txt',
    'data_dir': 'data',
    'result_path': 'result',
    'sample_file': None,
    "attribution_map_path": "temp/debias/gpt-j-6b/attribution_map",
    'neuron_path': 'temp/debias/gpt-j-6b/neurons-ig-grad.pt',
    'weight_path': 'temp/debias/gpt-j-6b/weights.npz',
}

bert_config_debias = {
    'model': 'bert',
    'structure': 'bi',
    'task_name': 'debias',
    'mask_id': 103,
    'device': 'cuda:0',
    'distributed_device': "0,1",
    'locate_method': 'ig',
    'erase_method': 'kv',
    'ca_ppl_delta': 0.1,
    'num_cuts': 20,
    'decomposite': 'V',
    'modify_weight': 'KV',
    'name_mlp': 'bert.encoder.layer.{}.mlp',
    'subname_K': 'K',
    'subname_V': 'V',
    'subname_act': 'act',
    'intermediate_size': 3072,
    'low_rank': True,
    'num_layers': 12,
    'chunk_size': 64,
    'num_local': 100,
    'seed': 42,
    'sample_rate': 1,
    'apply_model_rewriting': True,
    'skip_first_layer': False,
    'skip_last_layer': False,
    'log_file': 'logs/logs_debias.txt',
    'data_dir': 'data',
    'result_path': 'result',
    'sample_file': None,
    "attribution_map_path": "temp/debias/bert-base-uncased/attribution_map",
    'neuron_path': 'temp/debias/bert-base-uncased/neurons-ig-grad.pt',
    'weight_path': 'temp/debias/bert-base-uncased/weights.npz',
}

bert_config_qa = {
    'model': 'bert',
    'structure': 'bi',
    'task_name': 'qa',
    'mask_id': 103,
    'device': 'cuda:0',
    'distributed_device': "0,1",
    'locate_method': 'ig',
    'erase_method': 'kv',
    'ca_ppl_delta': 0.1,
    'num_cuts': 20,
    'decomposite': 'KV',
    'modify_weight': 'KV',
    'name_mlp': 'bert.encoder.layer.{}.mlp',
    'subname_K': 'K',
    'subname_V': 'V',
    'subname_act': 'act',
    'intermediate_size': 3072,
    'low_rank': True,
    'num_layers': 12,
    'chunk_size': 64,
    'num_local': 100,
    'seed': 42,
    'sample_rate': 0.25,
    'apply_model_rewriting': True,
    'skip_first_layer': False,
    'skip_last_layer': False,
    'log_file': 'logs/logs_qa_bert.txt',
    'data_dir': 'data',
    'result_path': 'result',
    'sample_file': None,
    "attribution_map_path": "temp/qa/bert-base-uncased/attribution_map",
    'neuron_path': 'temp/qa/bert-base-uncased/neurons-ig-grad.pt',
    'weight_path': 'temp/qa/bert-base-uncased/weights.npz',
}

gpt2_config = {
    'model': 'gpt2',
    'structure': 'uni',
    'device': 'cuda:0',
    'distributed_device': ['cuda:0', 'cuda:1'],
    'top_num': 3,
    'locate_method': 'ca',
    'erase_method': 'kv',
    'ca_ppl_delta': 0.1,
    'num_cuts': 10,
    'decomposite': 'V',
    'modify_weight': 'V',
    'name_mlp': 'transformer.h.{}.mlp',
    'subname_K': 'fc_in',
    'subname_V': 'fc_out',
    'subname_act': 'act',
    'intermediate_size': 6400,
    'low_rank': True,
    'num_layers': 48,
    'lambda': 1,
    'ortho_coef': 1,
    'entro_coef': 1,
    'recon_coef': 1,
    'lr': 1e-4,
    'num_epochs': 100,
    'chunk_size': 128,
    'num_local': 100,
    'seed': 42,
    'sample_rate': 0.1,
    'index_wise': True,
    'apply_model_rewriting': True,
    'skip_first_layer': False,
    'skip_last_layer': False,
    'data_dir': 'data',
    'result_path': 'result',
    'local_data_dir': 'data/wikipedia',
    'sample_file': 'temp/gpt2/sample_ids.json',
    'neuron_path': 'temp/gpt2/neurons-ca.pt',
    'weight_path': 'temp/gpt2/weights.npz',
}

# Set the LLM_DIR environment variable to your local model directory,
# or override the paths below to point to your own model checkpoints.
import os as _os
_LLM_DIR = _os.environ.get("LLM_DIR", "./models")
model_dict = {
    "gptj": (_os.path.join(_LLM_DIR, "gpt-j-6b"), GPTJForCausalLM),
    "gpt2": (_os.path.join(_LLM_DIR, "gpt2-xl"), GPT2LMHeadModel),
    "bert": (_os.path.join(_LLM_DIR, "bert-base-uncased"), BertForMaskedLM),
}
